# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
TMDB_API_KEY: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMjc1MmE0OTQ4MjhiZDEzMDE1ZmFmZDNlZTUzMDY2MiIsInN1YiI6IjY0MWE0MjFkOTVjMGFmMDBmNzA3NTM4OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5_qW_OU0h4RlmtOhFxNwJTQpX7N0K7DVzTfb5i6-rsw'